# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"double": "00_extra_math.ipynb",
         "triple": "00_extra_math.ipynb"}

modules = ["extra_math.py"]

doc_url = "https://gstaff.github.io/nbdev_test/"

git_url = "https://github.com/gstaff/nbdev_test/tree/master/"

def custom_doc_links(name): return None
